# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/munch/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

LOCAL_ALLOW_UNDEFINED_SYMBOLS := true

ifeq ($(TARGET_DEVICE),munch)

endif
